### ISSUE TITLE
I have add issue.

### ISSUE THREAD

**Issue by SungHyeon** [tech-sketch/zabbix_aws_template#15]
Zabbix version : 3.4
OS : Amazon Linux
Python : 2.7 (add boto3)

I think problem this zabbix template.

Can you help, please?

![issue](https://cloud.githubusercontent.com/assets/11917328/26381730/cdb0088a-4061-11e7-96b0-6d6d03b809b8.PNG)
![issue2](https://cloud.githubusercontent.com/assets/11917328/26381934/54508198-4063-11e7-9e2c-4abbacbc187a.PNG)

**Comment by SungHyeon** [comment]
I found discovery error....
why occured message.?
![issue3](https://cloud.githubusercontent.com/assets/11917328/26382444/2f835b48-4067-11e7-947d-737b1c82642b.PNG)

**Comment by ike-dai** [comment]
Thank you for your post.
Has it solved already?
I wonder why LLD process has failed.
